[package]
name = "psbt_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = {version = "0.32.2",features = ["default","serde"]}
hex = "0.4.3"
serde_json = "1.0.117"
